version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ethnodes-dockerfile
    image: "mysql:5.7-ethnodes"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./configs:/etc/mysql/conf.d
      - ${MYSQL_DIR}:/var/lib/mysql
      - ${BACKUP_DIR}:/backup
    ports:
      - "3306:3306"
    restart: always
