version: '3'
services:
  mysql:
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./configs:/etc/mysql/conf.d
      - ${DATADIR_ROOT}:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
